version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./config/wallet.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8089:80"
    expose:
      - "8089"
    depends_on:
      - eth
      - btc

  database:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql/database.sql:/docker-entrypoint-initdb.d/wallet.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    command: --requirepass abcd
    ports:
      - "6379:6379"
    expose:
      - "6379"

  eth:
    container_name: wallet-eth
    build:
      context: .
      args:
        coin: eth
        port: 8037
    volumes:
      - /var/log/wallet/eth:/app/logs
    depends_on:
      - database
      - redis

  btc:
    container_name: wallet-btc
    build:
      context: .
      args:
        coin: btc
        port: 8038
    volumes:
      - /var/log/wallet/btc:/app/logs
    depends_on:
      - database
      - redis