version: '3'
services:
  database:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql/database.sql:/docker-entrypoint-initdb.d/wallet.sql
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis
    environment:
      - REDIS_AUTH=abcd
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - "6379"
    command: redis-server --protected-mode yes --requirepass "$$REDIS_AUTH"

  wallet-service:
    build: .
    depends_on:
      - database
      - redis
    volumes:
      - ~/.ssh:/home/root/.ssh/id_rsa
    ports:
      - "8037:8037"