version: '3'
services:
  nginx:
    image: nginx
    expose: 8080

  database:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql/database.sql:/docker-entrypoint-initdb.d/wallet.sql
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - "6379"
    command: --requirepass abcd

  eth:
    container_name: wallet-eth
    build:
      context: .
      args:
        coin: eth
        port: 8037
    depends_on:
      - database
      - redis
    ports:
      - "8037:8037"

  btc:
    container_name: wallet-btc
    build:
      context: .
      args:
        coin: btc
        port: 8038
    depends_on:
      - database
      - redis
    ports:
      - "8038:8038"